### ISSUE TITLE
Should be able to set output with CLI flags

### ISSUE THREAD

**Issue by mikkotikkanen** [michaelleeallen/mocha-junit-reporter#10]
It would make sense to be able to set the report output from CLI flags, ie. `--report=unit-tests.xml`, this would make fe. npm scripts cleaner and more portable.

Another option would be able to supress generated output altogether and do it the way jshint & jscs do it, with stdout redirect ie. `--no-report > test-output/mocha-tests.xml`.

**Comment by clayreimann** [comment]
The first part of this issue should be fixed now thanks to #9, are you actually interested in printing the results to the console?

**Comment by mikkotikkanen** [comment]
This seems to be quite common way to do things so that you can then pipe the output directly to whatever file/program you wish. So yeah, I think it would be a useful addition. fe. jscs and jshint seem to do it like so.
