### ISSUE TITLE
Package name showing as “root” in Jenkin pipeline with cypress junit reporter

### ISSUE THREAD

**Issue by sabf81** [michaelleeallen/mocha-junit-reporter#136]
We are using Cypress with JUnit Reporter.
Out test-suite runs in Jenkin. But in Jenkin's Junit test result the package name always shows root.

How can I change it from root to any other name?

![root-package-name](https://user-images.githubusercontent.com/13674691/94234395-e3365a00-ff09-11ea-85e3-d79aa50d6ebf.gif)

Config of reporter:
<img width="546" alt="reporter-config json" src="https://user-images.githubusercontent.com/13674691/94234736-8edfaa00-ff0a-11ea-9803-3a6aa6933263.png">

Test Example:
<img width="1156" alt=" test spec ts" src="https://user-images.githubusercontent.com/13674691/94234751-956e2180-ff0a-11ea-812a-b780ad31a60f.png">

**Comment by prnsml** [comment]
Hi currently there isn't an option for that, I had the same issue :/
Created PR to fix this https://github.com/michaelleeallen/mocha-junit-reporter/pull/138

For now, you can use this patched reporter directly if you don't want to wait.
For example, I have [this reporter](https://raw.githubusercontent.com/michaelleeallen/mocha-junit-reporter/61a9d3e2aee289f328e80aba69570cd6dc6c427a/index.js) in cypress/reporters/jenkins.js
and here is part of my cypress.json:
```
  "reporter": "cypress/reporters/jenkins.js",
  "reporterOptions": {
    "mochaFile": "cypress/reports/cypress-report-[hash].xml",
    "jenkinsMode": true,
    "jenkinsClassnamePrefix": "E2E Tests",
    "toConsole": true
  },
```

**Comment by prnsml** [comment]
Released patched version for those who are impatient as I am :)
https://www.npmjs.com/package/@prnsml/mocha-junit-reporter
1. ``` npm install @prnsml/mocha-junit-reporter@2.1.1 --save-dev```
2. Set reporter to `@prnsml/mocha-junit-reporter`  
3. Add `jenkinsClassnamePrefix` with your prefered prefix to `reporterOptions`
4. 😎

**Comment by sabf81** [comment]
@michaelleeallen can please accept the PR #138 to fix it? 
Thanks.

**Comment by k3n** [comment]
Bump :) Love this project and that it caters to Jenkins, and this would be a nice QoL improvement.

**Comment by baviereteam** [comment]
Bump too : this would make it way easier to easily split different test levels / sources / suites in Jenkins :)

**Comment by clayreimann** [comment]
#138 was merged about a month age, this should be available now
