### ISSUE TITLE
Publish 2.1.0 to NPM

### ISSUE THREAD

**Issue by Turbotailz** [michaelleeallen/mocha-junit-reporter#176]
@michaelleeallen @clayreimann can we please have 2.1.0 published to NPM?

**Comment by clayreimann** [comment]
It should happen automatically. Let me check on what happened

**Comment by Turbotailz** [comment]
Probably worth noting that this seemed to also happen with 2.0.1 - #142

**Comment by clayreimann** [comment]
@Turbotailz I figured out why things weren't working, version `2.1.0` should be going out to NPM as we speak
