### ISSUE TITLE
mocha-junit-reporter doesn't work with grep '^'

### ISSUE THREAD

**Issue by junminstorage** [michaelleeallen/mocha-junit-reporter#30]
**Test result**
I have some test cases with describe('mocked tests') and some with describe('unmocked test'). 

./node_modules/mocha/bin/mocha --invert --grep 'unmocked' -R mocha-junit-reporter 
runs unmocked test cases. 

./node_modules/mocha/bin/mocha --invert --grep '^unmocked' -R mocha-junit-reporter
runs both unmocked and mocked test cases. 

**What should be expected?**

./node_modules/mocha/bin/mocha --invert --grep '^unmocked' -R mocha-junit-reporter
should run 'unmocked' test cases only.

**Comment by clayreimann** [comment]
This sounds like a problem with either your `mocha` command or with `mocha` itself. 

Does this work correctly with one of the build in reporters?

**Comment by junminstorage** [comment]
The built-in mocha reporters like xunit works as expected. 
I was trying to look at the difference between xunit reporter and this junit reporter, but didn't find any clue yet.

**Comment by guyellis** [comment]
I'm seeing something similar with `it.only` and `describe.only` which (I believe) uses grep under the covers which is why I'm adding to this issue instead of creating a new one.

Using the built in reporters it will run the relevant `.only()` test. With mocha-junit-reporter it will not.

**Comment by michaelleeallen** [comment]
Now that v1.12 has been released which includes support for Mocha v3x, we may need to revisit this issue to see if it is still relevant. 

Per mochajs.org:
> Previous to v3.0.0, .only() used string matching to decide which tests to execute. As of v3.0.0, this is no longer the case.

**Comment by michaelleeallen** [comment]
@junminstorage + @guyellis I started looking into this problem but I have found that mocha will not run `^` regexes even without a reporter specified. Can one of you verify this with your code base?

**Comment by guyellis** [comment]
@michaelleeallen - I'm not working on that project anymore and so I don't have access to that code base anymore. Sorry I can't help further.

**Comment by junminstorage** [comment]
Yes, that is true.
the ^ is completely ignored by mocha now.

**Comment by michaelleeallen** [comment]
Ok. So, it seems like this is an issue with mocha and not mocha-junit-reporter. I am going to close this issue if everyone agrees.

**Comment by junminstorage** [comment]
Yes, close it. We can reopen it once it resurfaces again.
