### ISSUE TITLE
Version 1.11.0 is 404ing - ಠ_ಠ 

### ISSUE THREAD

**Issue by marcusellis05** [michaelleeallen/mocha-junit-reporter#32]
Not sure if this a problem on the npm side or not, but thought you should know.

```
$ npm install mocha-junit-reporter
npm ERR! fetch failed https://registry.npmjs.org/mocha-junit-reporter/-/mocha-junit-reporter-1.11.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/mocha-junit-reporter/-/mocha-junit-reporter-1.11.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

**Comment by clayreimann** [comment]
Thanks for the heads up. I hope this is a problem on npm's side but I'll check the logs from the travis build.

**Comment by JADurham909** [comment]
Having the same issue.. I posted an issue on NPM.  

https://github.com/npm/npm/issues/12369

npm ERR! fetch failed https://registry.npmjs.org/mocha-junit-reporter/-/mocha-junit-reporter-1.11.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

**Comment by clayreimann** [comment]
I have a support ticket open with NPM, looks like they had an issue with their tarball serving this afternoon.

**Comment by clayreimann** [comment]
I've pushed `v1.11.1` which, based on the incident report, should clear up the issue.
