### ISSUE TITLE
DSL Publisher options

### ISSUE THREAD

**Issue by DeChrish** [michaelleeallen/mocha-junit-reporter#35]
Hi, 
 i am using dsl to create jenkins jobs,
Can you please add dsl publisher groovy file for mocha-juint-reporter

sample dsl Publishers : https://github.com/jenkinsci/job-dsl-plugin/tree/master/job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext

**Comment by clayreimann** [comment]
@DeChrish I'm not sure what you're asking for here. This is a javascript library, we don't have any groovy code, nor do we directly integrate with `jenkins` we just format [`mocha`](http://mochajs.org/) test results as junit xml.

**Comment by clayreimann** [comment]
Closing. If this is actually our issue and you have more information then feel free to reopen.
