### ISSUE TITLE
Update npm

### ISSUE THREAD

**Issue by MattJeanes** [michaelleeallen/mocha-junit-reporter#40]
Hi there,

Can you please update your npm repository? The bug fixed in https://github.com/michaelleeallen/mocha-junit-reporter/commit/41615f2edbe5a2e82f1a375ace232114c4b92589 caused me quite a bit of trouble until I realised that npm was out of sync with GitHub.

Thanks!

**Comment by randallagordon** [comment]
Same here, would love to see this fix get published!

**Comment by clayreimann** [comment]
Just pushed a new tag `1.12.1` should be available shortly. Sorry for the slowness.

**Comment by MattJeanes** [comment]
Thanks!
