### ISSUE TITLE
Test output in JUnit report files

### ISSUE THREAD

**Issue by eskatos** [michaelleeallen/mocha-junit-reporter#48]
The generated JUnit report files do not include any test output.
It would be awesome that they do.

**Comment by michaelleeallen** [comment]
@eskatos Providing an example of your issue, or other useful information would be help since no one else has commented on having the same issue.

**Comment by eskatos** [comment]
I'm thinking of the output of each test in the `stdout`/`stderr` sense.

The JUnit XML file format allows to embed this, e.g.:

```xml
<testsuites>
  <testsuite>
    <testcase>
      <system-out>
        => data written to System.out during the test run
      </system-out>
      <system-err>
        => data written to System.err during the test run
      </system-err>
      ...
    </testcase>
  </testsuite>
</testsuites>
```

So, the actual behavior is that if my tests do write some output to `stdout` or `stderr` I can see it on the console but it's not recorded in the JUnit result files. Having this output saved for later scrutiny would be of great help.

I opened this issue more as a feature request than as a bug report. Sorry if it wasn't clear.

**Comment by hrdk108** [comment]
@michaelleeallen Can we have this feature?

**Comment by clayreimann** [comment]
@hrdk108 You're more than welcome to open a PR.

**Comment by grawk** [comment]
+1 to this feature... would help especially if the test output may have paths to screenshots etc.
