### ISSUE TITLE
incompatibility with mocha ver. 4

### ISSUE THREAD

**Issue by tkratky** [michaelleeallen/mocha-junit-reporter#54]
npm WARN mocha-junit-reporter@1.14.0 requires a peer of mocha@^3 || ^2.2.5 but none is installed. You must install peer dependencies yourself
https://github.com/mochajs/mocha/releases

**Comment by clayreimann** [comment]
Looks like there weren't any breaking changes for reporters in `4.x`, I'll list `4.x` in the peerDependencies. If you run into any issues please let us know.

**Comment by clayreimann** [comment]
closed in 4e9fc12
