### ISSUE TITLE
Nested describes - wrong xml output.

### ISSUE THREAD

**Issue by Zarion** [michaelleeallen/mocha-junit-reporter#55]
I have problem with export mocha test results to xml file. I need this to create report on Hiptest in test run for external tests.

I'm using mocha-junit-reporter, but there is a problem with nested describes. I will try to explain this on example:

```
describe("Tests", function(){
  describe("Describe 1", function(){
    it("Test 1", function(){
      //Some code
    }); 
    describe("Describe 2", function(){   
      it("Test 2", function(){
        //Some code
      });
      it("Test 3", function(){
        //Some code
      });
    });
    describe("Describe 3", function(){   
      it("Test 4", function(){
        //Some code
      });
      it("Test 5", function(){
        //Some code
      });
    });
  });
});
```
Mocha result:

```
Tests
   Describe 1
   1) Test 1
      Describe 2
         2) Test 2
         3) Test 3
      Describe 3
         4) Test 4
         5) Test 5
```
As a result in xml file I recieve:

```
Describe 1:
   - Test 1
Describe 2:
   - Test 2
   - Test 3
Describe 3:
   - Test 4
   - Test 5
```

Each describe is analyzed as a separate test suite. So in result top describe is ignored, beacuse there is no tests in it. Describe 2 and Describe 3 are not nested in Describe 1.

I don't know how to achive result i need.

**Comment by clayreimann** [comment]
Is there a reason you need your XML to be nested like your test suites? 

Also, don't your test suite names look like `Describe 1`, `Describe 1.Describe 2`, `Describe 1.Describe 3`?

**Comment by Zarion** [comment]
Like i said, I need this to achieve test structure on raport in Hiptest as a external tests (without Hiptest publisher). This is transitional step to separete tests form Hiptest. But we need to keep current structure on report.

> Also, don't your test suite names look like Describe 1, Describe 1.Describe 2, Describe 1.Describe 3?

No its just: Describe 1, Describe 2, Describe 3.
Testcase name looks like: Tests.Describe 1.Describe 2.Test 3.

**Comment by belimm01** [comment]
@Zarion did you find the answer to this issue?

**Comment by michaelleeallen** [comment]
@Zarion mocha-junit-reporter is in compliance with the jUnit test report spec. In order to support your request we would have to change the expected output(which doesnt match test suite structure) which IMO is a major, breaking change. You are free to fork this repo and modify to suite your needs.

**Comment by ringods** [comment]
Linking to ongoing work regarding standardizing the output format:

* https://github.com/ota4j-team/opentest4j/issues/9
* https://github.com/junit-team/junit5/issues/373
