### ISSUE TITLE
No results.xml output

### ISSUE THREAD

**Issue by kraftman** [michaelleeallen/mocha-junit-reporter#56]
Struggling to work out how to debug this.
I have a set of nested folders with tests in them, if I run each subfolder individually, each one will generate a test-result.xml file without any issues.

If I run the whole folder, I get no test-results.xml file.
For example if I run this in package.json:
`mocha --reporter mocha-junit-reporter --reporter-options useFullSuiteTitle=true 'path/to/test/**/*_SlowTest.js'; exit 0`
It will work, however this will not:
`mocha --reporter mocha-junit-reporter --reporter-options useFullSuiteTitle=true 'path/to/**/*_SlowTest.js'; exit 0`

Running the same command without the --reporter shows that all tests are running (some are failing but that shouldnt matter)
My guess that there is some error preventing the .xml getting generated, but I have no idea where to start with finding out where, since each individual set of tests works without issue.

**Comment by clayreimann** [comment]
Try using `DEBUG= mocha-junit-reporter mocha --reporter mocha-junit-reporter --reporter-options useFullSuiteTitle=true 'path/to/**/*_SlowTest.js'; exit 0`. That should give you [some data](https://github.com/michaelleeallen/mocha-junit-reporter/blob/master/index.js#L307-L315) for your hunch.

**Comment by kraftman** [comment]
Thanks  a lot, I'll give it a go!

**Comment by kraftman** [comment]
Yeah looks like the _runner.on('end' function isnt called at all when running the whole folder of subtests, really odd.

**Comment by clayreimann** [comment]
You could try running `DEBUG=*` I believe that mocha uses the debug package too. Might yield more information for you to open an issue with them.

Closing for now since it doesn't appear to be an issue with the reporter. If you determine that we are at fault some how (perhaps by a liberal use of more debug statements) please reopen with and attach a minimal example demonstrating the problem.
