### ISSUE TITLE
incompatibility with mocha ver. 5

### ISSUE THREAD

**Issue by tkratky** [michaelleeallen/mocha-junit-reporter#58]
Hi,

can you add mocha ver.5 into package.json?

npm ERR! peerinvalid The package mocha@5.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mocha-junit-reporter@1.15.0 wants mocha@^4 || ^3 || ^2.2.5

Thank you

**Comment by clayreimann** [comment]
This should be fixed in `1.16.0`, which should be out soon
