### ISSUE TITLE
XML output schema validation

### ISSUE THREAD

**Issue by lukewis** [michaelleeallen/mocha-junit-reporter#66]
I'm currently using this package to generate junit-style test results to be uploaded to Microsoft Visual Studio Team Services.  The vsts team said that they currently validate junit results against [this schema](https://github.com/windyroad/JUnit-Schema).  However, the output from this package currently fails to validate against that schema.  Is there a different schema that you're currently validating against?  Is it possible for output to be altered to pass validation against the one that the vsts team is using?

**Comment by lukewis** [comment]
Here's a sample generated file
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="1" failures="0" skipped="1">
  <testsuite name="Root Suite" timestamp="2018-08-30T09:59:02" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="default" timestamp="2018-08-30T09:59:02" tests="1" file="/Users/lawisnie/source/sandbox/tests/default.spec.js" failures="0" time="0">
  </testsuite>
</testsuites>
```
The validation errors (against the mentioned schema) are:
```
Line 2 Column 76 : cvc-complex-type.3.2.2: Attribute 'name' is not allowed to appear in element 'testsuites'.
Line 2 Column 76 : cvc-complex-type.3.2.2: Attribute 'time' is not allowed to appear in element 'testsuites'.
Line 2 Column 76 : cvc-complex-type.3.2.2: Attribute 'tests' is not allowed to appear in element 'testsuites'.
Line 2 Column 76 : cvc-complex-type.3.2.2: Attribute 'failures' is not allowed to appear in element 'testsuites'.
Line 2 Column 76 : cvc-complex-type.3.2.2: Attribute 'skipped' is not allowed to appear in element 'testsuites'.
Line 3 Column 96 : cvc-complex-type.4: Attribute 'package' must appear on element 'testsuite'.
Line 3 Column 96 : cvc-complex-type.4: Attribute 'id' must appear on element 'testsuite'.
Line 3 Column 96 : cvc-complex-type.4: Attribute 'hostname' must appear on element 'testsuite'.
Line 3 Column 96 : cvc-complex-type.4: Attribute 'errors' must appear on element 'testsuite'.
Line 4 Column 15 : cvc-complex-type.2.4.b: The content of element 'testsuite' is not complete. One of '{properties}' is expected.
Line 5 Column 153 : cvc-complex-type.3.2.2: Attribute 'file' is not allowed to appear in element 'testsuite'.
Line 5 Column 153 : cvc-complex-type.4: Attribute 'package' must appear on element 'testsuite'.
Line 5 Column 153 : cvc-complex-type.4: Attribute 'id' must appear on element 'testsuite'.
Line 5 Column 153 : cvc-complex-type.4: Attribute 'hostname' must appear on element 'testsuite'.
Line 5 Column 153 : cvc-complex-type.4: Attribute 'errors' must appear on element 'testsuite'.
Line 6 Column 15 : cvc-complex-type.2.4.b: The content of element 'testsuite' is not complete. One of '{properties}' is expected.
```
It looks like it would be a significant change to the output in order to validate against this schema, many of which would be "breaking changes" (i.e. removing attributes like name, time, tests, failures), so I can understand if this is out of scope, I was just trying to get a better understanding of what the original intent of this tool was.  It's possible that supporting the schema used by vsts should be a separate project, but I wanted to have the discussion here first.

**Comment by clayreimann** [comment]
It’s a fair ask. I know that my company uses this package successfully in conjunction with the Travis Junit plugin. 

I think we could accommodate the different output schema by adding a new serializer behind a flag. There’s a relatively small amount of code that actually does the XML writing 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by michaelleeallen** [comment]
Hi @lukewis when I originally created this module I loosely followed the schema you referenced. I made it work for my use case(integrate with Bamboo). I think it would be a good idea to make this module compliant with the official JUnit XSD, and in fact I have done so with my other module[ jest-junit-reporter](https://github.com/michaelleeallen/jest-junit-reporter/blob/master/src/__tests__/fixtures/junit.xsd). Unfortunately I do not have time to maintain this module any more. I am going to mark this issue as an enhancement and let the community handle it.

**Comment by clayreimann** [comment]
@michaelleeallen is that scheme official? I couldn’t see any indication that it was canonical

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clayreimann** [comment]
`jenkinsMode` or `antMode` should resolve this

**Comment by ckoncz-hwx** [comment]
I am using mocha-junit-reporter with Cypress 6.0 and I do get an extra `file` attribute on the root suite even when using `antMode` or `jenkinsMode` (or both).
