### ISSUE TITLE
404 when installing mocha-junit-reporter v1.3.0

### ISSUE THREAD

**Issue by branneman** [michaelleeallen/mocha-junit-reporter#7]
I get this error when running `npm install mocha-junit-reporter`:

![image](https://cloud.githubusercontent.com/assets/172579/7517701/dea88aa0-f4d6-11e4-8ed8-1501f027c654.png)

You've said in pull #3 that you've set up travis-ci to do auto deployments to npm, maybe something goes bad there?

It seems impossible to install 1.3 - but 1.2 works.

**Comment by michaelleeallen** [comment]
Oh crap. Let me take a look.

**Comment by mallenscdhhs** [comment]
I can verify that NPM has v1.3.0, and github also has that tagged commit. When I run `npm install mocha-unit-reporter` it pulls down v1.3.0. Maybe clear your NPM cache?

**Comment by michaelleeallen** [comment]
I can verify that NPM has v1.3.0, and github also has that tagged commit. When I run `npm install mocha-junit-reporter` it pulls down v1.3.0. Maybe clear your NPM cache?

**Comment by branneman** [comment]
Euhm, I'm pretty sure this one is on your side or npm's side. I just got a new MacBook today, and I still got the problem, while again, it does work on v1.2.

I think the `npm publish` somehow failed. Maybe do it again, manually? Or first `npm unpublish`?

**Comment by branneman** [comment]
Also, this url gives me a 404 in my browser as well, from different computers, on different WiFi's:
https://registry.npmjs.org/mocha-junit-reporter/-/mocha-junit-reporter-1.3.0.tgz

**Comment by michaelleeallen** [comment]
Ok, I am able to reproduce this on cloud9. I will have to take a look at it later tonight, but in the mean time could you try pointing your package.json to:
```javascript
{
  "devDependencies": {
    "mocha-junit-reporter": "michaelleeallen/moch-junit-reporter",
    ...
  }
}
```
