### ISSUE TITLE
Update npm version

### ISSUE THREAD

**Issue by PeterNgTr** [michaelleeallen/mocha-junit-reporter#79]
The npm version seemed to be out of sync with github, due to missing the adding attachments for test. Could we consider publishing new version to npm soon? 

Cause I want use the attachment feature with [codeceptjs](https://github.com/Codeception/CodeceptJS/issues/1502), but then realised it's not there yet in npm

Thanks!

**Comment by clayreimann** [comment]
@PeterNgTr Done, sorry I forgot to do that after I merged the PR. New version is now live on npm
