### ISSUE TITLE
Testing: Actually invoke mocha instead of mocking it out

### ISSUE THREAD

**Issue by clayreimann** [michaelleeallen/mocha-junit-reporter#83]
It was [suggested][suggestion], and would be a good idea, to actually invoke mocha from inside our tests to ensure that we conform to mocha's API.

Ironically, it may be necessary to use a separate test driver in order to actually accomplish this.

[suggestion]: https://github.com/michaelleeallen/mocha-junit-reporter/pull/82#discussion_r270870971

**Comment by gabegorelick** [comment]
I've taken a stab at this in https://github.com/michaelleeallen/mocha-junit-reporter/pull/120. So far it's highlighted a few potential bugs and some issues where the tests were making assumptions that weren't true.
