### ISSUE TITLE
Set an attachment in AfterEach hook

### ISSUE THREAD

**Issue by rodney-wilson** [michaelleeallen/mocha-junit-reporter#85]
I'm trying to set an attachments with absolute path to a screenshot in case if a test failed in AfterEach hook.

`this.test.attachments = [absolutePath]` works great from test. But when I moved that line to AfterEach hook it stopped working.
I've tried to use the following and an attachment wasn't added: 
`this.test.attachments = [absolutePath]; `
`this.currentTest.attachments = [absolutePath];` 
`this.currentTest.ctx.attachments = [absolutePath];`
`this.test.ctx.attachments = [absolutePath];`

Is there any way to attach a screenshot path from AfterEach hook?

**Comment by clayreimann** [comment]
This looks more like a Mocha question and less like a junit-reporter question. Did I miss something?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rodney-wilson** [comment]
Thanks. I will raise the issue with Mocha.

**Comment by Remimstr** [comment]
Hey @rodney-wilson Did you ever figure this out?

**Comment by Remimstr** [comment]
@rodney-wilson Fair enough I totally get that. Thanks for getting back to me!
